"""Add new columns

Revision ID: dde5d80cc0c5
Revises: 3034b0250668
Create Date: 2026-03-08 21:18:46.798671

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dde5d80cc0c5"
down_revision: Union[str, Sequence[str], None] = "3034b0250668"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("escalations", schema=None) as batch_op:
        batch_op.alter_column(
            "operator_name", existing_type=sa.VARCHAR(length=100), type_=sa.String(length=64), existing_nullable=True
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("response_time_ms", sa.Integer(), nullable=True))

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_type", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("urgency", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("wechat_qr_image_path", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("wechat_added", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("wecom_chat_id", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("wecom_chat_id")
        batch_op.drop_column("wechat_added")
        batch_op.drop_column("wechat_qr_image_path")
        batch_op.drop_column("urgency")
        batch_op.drop_column("order_type")

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_column("response_time_ms")

    with op.batch_alter_table("escalations", schema=None) as batch_op:
        batch_op.alter_column(
            "operator_name", existing_type=sa.String(length=64), type_=sa.VARCHAR(length=100), existing_nullable=True
        )

    # ### end Alembic commands ###
