[program:pdd_bot_web]
command=python3 main.py
directory=/Users/admin/Desktop/pdd-e-commerce-bot
autostart=true
autorestart=true
stderr_logfile=/Users/admin/Desktop/pdd-e-commerce-bot/logs/web.err.log
stdout_logfile=/Users/admin/Desktop/pdd-e-commerce-bot/logs/web.out.log
environment=PYTHONPATH="/Users/admin/Desktop/pdd-e-commerce-bot"

[program:pdd_bot_worker]
command=python3 worker.py
directory=/Users/admin/Desktop/pdd-e-commerce-bot
autostart=true
autorestart=true
stderr_logfile=/Users/admin/Desktop/pdd-e-commerce-bot/logs/worker.err.log
stdout_logfile=/Users/admin/Desktop/pdd-e-commerce-bot/logs/worker.out.log
environment=PYTHONPATH="/Users/admin/Desktop/pdd-e-commerce-bot"
